# angfind-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: angfind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angfind
  template:
    metadata:
      labels:
        app: angfind
    spec:
      containers:
        - name: angfind
          image: angfind:latest
